name: Terraform Infras

on:
  push:
    branches:
      - feature/pipeline-tf

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Checkout Terraform Repository
      uses: actions/checkout@v2
      with:
        repository: Pos-Tech-Challenge-48/eks-tf

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v1
    #   with:
    #     terraform_version: 0.14.0

    # - name: Terraform Format
    #   id: fmt
    #   run: terraform fmt -check

    # - name: Terraform Init
    #   run: terraform init
      
    # - name: Terraform Plan
    #   run: terraform plan
      
    # - name: Terraform Apply
    #   working-directory: ./terraform-config
    #   run: terraform apply -auto-approve