version: '3.8'

services:
  db:
    profiles:
    - "db"
    - "full"
    container_name: postgres-server
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - delivery-network
    ports:
      - 5432:5432
    volumes:
      - delivery-postgresdb:/var/lib/postgresql/data

volumes:
  delivery-postgresdb:

networks:
  delivery-network:
    name: delivery-network
