apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-api
  labels:
    app: delivery-api
spec:
  template:
    metadata:
      name: delivery-api
      labels:
        app: delivery-api
    spec:
      containers:
        - name: delivery-api-container
          image: vitorsmap/delivery-api:v3
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: "0.5"
              memory: 512Mi
            limits:
              cpu: "1.0"
              memory: 512Mi
          env:
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: api-config
                key: ENVIRONMENT
          - name: POSTGRESQL_URL
            valueFrom:
              configMapKeyRef:
                name: api-config
                key: POSTGRESQL_URL
  replicas: 1
  selector:
    matchLabels:
      app: delivery-api
