name: 🚀 Build and Deploy
run-name: 🌴 ${{ github.ref_name }} | ${{ github.event.inputs.environment }} | Deploying...

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: 📦 Building ${{ github.ref_name }}...
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "delivery-api"
          IMAGE_TAG: ${{github.ref_name}}
        run: |
          docker build -t delivery-api:prod . \
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Write File
        uses: actions/create-file@v1
        env:
          POSTGRESQL_URL: ${{ secrets.POSTGRESQL_URL }}
        with:
          path: ./kubernetes/api/api-configmap.yaml
          content: | 
            <<EOF
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: my-configmap
            data:
              POSTGRESQL_URL: $POSTGRESQL_URL
              ENVIRONMENT: production
            EOF


      - name: Deploy to AWS EKS
        uses: giovannirossini/aws-eks@v1.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'sa-east-1'
          cluster-name: 'cluster-example'
          command: |
            kubectl apply -f ./kubernetes/api
          
        

      